### ISSUE TITLE
在docker中部署以后网页404 not found。

### ISSUE THREAD

**Issue by hxj0316** [Zeyi-Lin/HivisionIDPhotos#10]
![image](https://github.com/xiaolin199912/HivisionIDPhotos/assets/66103957/40f567eb-120e-47a6-9403-5ec9e733435f)您好，我在docker中编译并完成部署以后，点击打开对应的网站，显示404not found，请问是什么原因导致的呢？

**Comment by houhoufm** [comment]
端口映射问题，docker内部端口不要修改，你可以在这样 -p 8080:7860
