### ISSUE TITLE
安装mtcnn-runtime默认安装高版本的onnxruntime，然后会覆盖掉onnxruntime-gpu，想问问怎么解决

### ISSUE THREAD

**Issue by badarrrr** [Zeyi-Lin/HivisionIDPhotos#114]
我是小白，我想请问一下，我之前没有用过mtcnn-runtime这个库；本来是想gpu加速推理的，我在环境里安装requirements里的mtcnn-runtime的时候，会自动安装1.19.2的onnxruntime；但是我的cuda和cudnn只能支持1.18.0的onnxruntime-gpu；
我现在安装了onnxruntime-gpu==1.18.0，但我import onnxruntime的时候还是会显示1.19.2版本的，且也不支持gpu

**Comment by badarrrr** [comment]
如果我先安装onnxruntime-gpu==1.18.0，没有安装mtcnn-runtime的时候，会显示gpu和1.18.0；但安装完mtcnn-runtime，就变成cpu和1.19.2了

**Comment by Zeyi-Lin** [comment]
你应该可以再pip install onnxruntime==1.18.0
