### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by qq727127158** [Zeyi-Lin/HivisionIDPhotos#12]
就使用dockerfile中的版本python3.10可以正常跑起，其他版本低了或者高了都会有依赖安装的问题。

**Comment by qq727127158** [comment]
Python >= 3.7  建议改成    3.10 < Python >= 3.7

**Comment by Zeyi-Lin** [comment]
安装依赖已大幅更新，docker安装应该不再有太多环境问题
