### ISSUE TITLE
v1.2.3中dpi选项的输出结果不正确

### ISSUE THREAD

**Issue by dscao** [Zeyi-Lin/HivisionIDPhotos#126]
刚测试了一下最新版，有dpi设置了，但结果下载后用ps打开，仍然是72像素/英寸，无论dpi设置是多少，图像尺寸还是一样大。不同dip应该不一样像素输出。

**Comment by Zeyi-Lin** [comment]
![image](https://github.com/user-attachments/assets/c000511b-b43f-4480-a2b2-718f6128b592)

你需要在这里下载

**Comment by dscao** [comment]
又试了一下，那里确实有dpi了，但如果用254dpi，或者600dpi时，照片尺寸就不对了。只能用300dpi打印才是正确的尺寸。
另外那六寸排版照，还需要在打印时先设置一下dpi。最好是下载排版照直接可打印需要的dpi及正确尺寸。

**Comment by Zeyi-Lin** [comment]
https://github.com/Zeyi-Lin/HivisionIDPhotos/pull/131 已支持排版照按照要求的DPI下载
