### ISSUE TITLE
demo app.py 报错显示 TypeError: IDPhotoProcessor._create_response() takes 6 positional arguments but 7 were given 

### ISSUE THREAD

**Issue by xrgan** [Zeyi-Lin/HivisionIDPhotos#138]
使用的是实例图片，报错如图，这是什么情况
TypeError: IDPhotoProcessor._create_response() takes 6 positional arguments but 7 were given
![d7a50b61652bcfcc3d252f822f3e51d](https://github.com/user-attachments/assets/2cfdf740-98e2-4e05-b386-8229e65e1a2a)
![764dcef763cfbcd75f3405d9300aaa5](https://github.com/user-attachments/assets/a31088c1-ce75-4fbc-867a-faab33f6cdfb)
![de2c842a91cd3e2172a9ee5f842ed0b](https://github.com/user-attachments/assets/fc89b01f-bcd9-4707-ad5f-107e2b636a49)

**Comment by xrgan** [comment]
我也没改代码啊，求大佬解惑

**Comment by Zeyi-Lin** [comment]
已修复，pull一下最新的代码

**Comment by xrgan** [comment]
ok ,问题解决了 
![image](https://github.com/user-attachments/assets/88eb96e8-360e-4ccb-af30-a6210a9ebd71)
