### ISSUE TITLE
must be share=True ,where is it?

### ISSUE THREAD

**Issue by fdzl22** [Zeyi-Lin/HivisionIDPhotos#157]
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by fdzl22** [comment]
Ok, I konw, if you open VPN, you must be close class(vpn),becasuse you pc have proxy setting

**Comment by Zeyi-Lin** [comment]
if you open VPN, you can set environment variable `no_proxy`.
for example:
```
export no_proxy=localhost,127.0.0.1
```

**Comment by fdzl22** [comment]
Ok,thank you.
