### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./hivision_modnet.onnx failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by shround2k** [Zeyi-Lin/HivisionIDPhotos#16]
不管是本地安装或者docker安装都报相同错误，网上说重新下载安装就可以解决，但是我重新下载安装了之后并不可以

**Comment by little1d** [comment]
@shround2k 您好，可以看一下你的操作系统和 python 版本这些信息吗？

**Comment by Zeyi-Lin** [comment]
已更新requirements.txt

**Comment by anyine** [comment]
我也遇到了
Traceback (most recent call last):
  File "/Users/anyine/Desktop/Learning/AI/HivisionIDPhotos/app.py", line 135, in <module>
    sess = onnxruntime.InferenceSession(HY_HUMAN_MATTING_WEIGHTS_PATH)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anyine/Desktop/Learning/AI/HivisionIDPhotos/myenv/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Users/anyine/Desktop/Learning/AI/HivisionIDPhotos/myenv/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 480, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./hivision_modnet.onnx failed:Protobuf parsing failed.

python 3.12 ，mac m3 arm64

**Comment by hubgit122** [comment]
最新的requirements.txt，完全重新构建，还是不行

> 已更新requirements.txt

**Comment by little1d** [comment]
@hubgit122 @anyine @shround2k 可以先尝试点击[这里](https://drive.usercontent.google.com/u/0/uc?id=1O4T4v_7gUacRKt9b8U2L7Qb3tf6n81Vk&export=download)下载模型文件，替换你 clone 得到的 hivision_modnet.onnx 文件，再试试运行。
一般来说主要会有两个原因，一个是模型文件，另一个是 onnxruntime 运行时

**Comment by Zeyi-Lin** [comment]
> @hubgit122 @anyine @shround2k 可以先尝试点击[这里](https://drive.usercontent.google.com/u/0/uc?id=1O4T4v_7gUacRKt9b8U2L7Qb3tf6n81Vk&export=download)下载模型文件，替换你 clone 得到的 hivision_modnet.onnx 文件，再试试运行。 一般来说主要会有两个原因，一个是模型文件，另一个是 onnxruntime 运行时

感谢回答，我把Git LFS这块取消一下，同时把镜像文件做一个

**Comment by hubgit122** [comment]
> @hubgit122 @anyine @shround2k 可以先尝试点击[这里](https://drive.usercontent.google.com/u/0/uc?id=1O4T4v_7gUacRKt9b8U2L7Qb3tf6n81Vk&export=download)下载模型文件，替换你 clone 得到的 hivision_modnet.onnx 文件，再试试运行。 一般来说主要会有两个原因，一个是模型文件，另一个是 onnxruntime 运行时

感谢，但是access denied。能用个浏览器private页面测试一下吗？应该你也下载不了

**Comment by Zeyi-Lin** [comment]
> > @hubgit122 @anyine @shround2k 可以先尝试点击[这里](https://drive.usercontent.google.com/u/0/uc?id=1O4T4v_7gUacRKt9b8U2L7Qb3tf6n81Vk&export=download)下载模型文件，替换你 clone 得到的 hivision_modnet.onnx 文件，再试试运行。 一般来说主要会有两个原因，一个是模型文件，另一个是 onnxruntime 运行时
> 
> 感谢，但是access denied。能用个浏览器private页面测试一下吗？应该你也下载不了

模型Release里有：https://github.com/Zeyi-Lin/HivisionIDPhotos/releases/tag/pretrained-model

**Comment by Zeyi-Lin** [comment]
fix此问题的方法：
1. 将Release中的权重文件放到项目根目录
2. pip install -r requirements.txt
