### ISSUE TITLE
Docker 版，在设置背景色的时候，某些色值渲染出来会不太正确

### ISSUE THREAD

**Issue by QuentinHsu** [Zeyi-Lin/HivisionIDPhotos#18]
使用 docker 版自部署时，在设置背景色的时候，某些色值渲染出来会不太正确

比如 `#845ec2`（132,94,194）

下面是使用你们官方提供的 demo 的渲染结果，正确
![image](https://github.com/user-attachments/assets/7908705f-0a08-4f9e-82f3-777c1564aae9)

下面是我自己本地部署使用同样色值，不正确
![image](https://github.com/user-attachments/assets/a2d87695-c521-4cac-8667-d8b5f526ffc2)

**Comment by Zeyi-Lin** [comment]
已修复此问题
