### ISSUE TITLE
add_background接口传入input_image_base64显示missing  input_image接口调用不成功

### ISSUE THREAD

**Issue by leyan-lian** [Zeyi-Lin/HivisionIDPhotos#196]
换背景颜色接口传入input_image文件可以调用成功，传入图片input_image_base64则调用不成功
接口返回结果：
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "body",
                "input_image"
            ],
            "msg": "Field required",
            "input": null
        }
    ]
}

**Comment by shen774411223d** [comment]
你好，请提供一下调用接口的入参。这个报错信息看起来大概率是入参格式不对。

如果你是前端 请将`input_image_base64` 放到 `new FormData()`中

**Comment by leyan-lian** [comment]
直接使用postman请求的。返回结果是这样的：
![1730265928684](https://github.com/user-attachments/assets/d646031d-e22e-48f5-91be-5b6a477705b4)

入参我放到附件中，请查收
[接口入参.md](https://github.com/user-attachments/files/17566568/default.md)

**Comment by shen774411223d** [comment]
> 直接使用postman请求的。返回结果是这样的： ![1730265928684](https://private-user-images.githubusercontent.com/92238151/381403803-d646031d-e22e-48f5-91be-5b6a477705b4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzgwNzMsIm5iZiI6MTczMDMzNzc3MywicGF0aCI6Ii85MjIzODE1MS8zODE0MDM4MDMtZDY0NjAzMWQtZTIyZS00OGY1LTkxYmUtNWI2YTQ3NzcwNWI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAxMjI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZjE3OTBkY2E3ODZlN2JlMzhjYTk2OWJmMWY2OTI1ZTAxYWY3ODYzZDM3YzM4MGVjYTc4YjkyYzI4N2MyYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fu0M_m30uGm15Nq6rAzKgMWdyZKrQ21Gj5UCn4u8Jug)
> 
> 入参我放到附件中，请查收 [接口入参.md](https://github.com/user-attachments/files/17566568/default.md)


你好，按照你给的demo，我这里是调用成功的。可以确定是你`Postman`中没有正确指定formdata格式导致的 切换到headers tab看下 `Content-Type` 是否为 `multipart/form-data` 下面是一个可以正常调用的curl 你可以把它导入postman 然后更改参数试下
```bash
curl --location --request POST 'your_ip/add_background' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Accept: */*' \
--header 'Host: api.shenxiaotian.cn' \
--header 'Connection: keep-alive' \
--header 'Content-Type: multipart/form-data; boundary=--------------------------499720530187719158461353' \
--form 'input_image_base64="your_input_image_base64"' \
--form 'color="438edb"' \
--form 'render="0"'
```

**Comment by leyan-lian** [comment]
我使用您给的这个curl导入到postman中，然后更改参数调用接口，还是报同样的错误。请求头的Content-Type是multipart/form-data。
![image](https://github.com/user-attachments/assets/4da40120-f61a-4450-8e7e-c606a08382e0)
![image](https://github.com/user-attachments/assets/0bdafd06-4408-4667-92d7-6a39dfffe34e)

**Comment by leyan-lian** [comment]
重新拉取最新版本后，问题解决了
