### ISSUE TITLE
English demo?

### ISSUE THREAD

**Issue by 9cento** [Zeyi-Lin/HivisionIDPhotos#26]
Is it possible to have a demo in english on Huggingface's spaces? I can't manage to use it as is, and the browser's translator doesn't pick the text

**Comment by Zeyi-Lin** [comment]
I am developing a multilingual demo version, and if everything goes smoothly, it will be released in a few hours.

**Comment by Zeyi-Lin** [comment]
🚀HuggingFace demo already updated：https://huggingface.co/spaces/TheEeeeLin/HivisionIDPhotos

**Comment by 9cento** [comment]
Thank you, great job!
