### ISSUE TITLE
docker部署出错（拉取的是arm架构的，x86机器需自己构建镜像）

### ISSUE THREAD

**Issue by houhoufm** [Zeyi-Lin/HivisionIDPhotos#27]
root@debian:~# docker run -p 7860:7860 linzeyi/hivision_idphotos:v1
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
exec /usr/bin/python3: exec format error

**Comment by zhouw1015** [comment]
> root@debian：~# docker run -p 7860：7860 linzeyi/hivision_idphotos：v1 警告：请求的镜像的平台 （linux/arm64/v8） 与检测到的主机平台 （linux/amd64/v4） 不匹配，并且没有请求特定平台 exec /usr/bin/python3：exec 格式错误

要用arm架构的服务器才行

**Comment by houhoufm** [comment]
我是x86的服务器，按作者的说明自己构建了镜像，能正常使用了。

**Comment by houhoufm** [comment]
我是x86的服务器，按作者的说明自己构建了镜像，能正常使用了。

**Comment by Zeyi-Lin** [comment]
感谢反馈，我将提醒增加到README中

**Comment by Zeyi-Lin** [comment]
#29
