### ISSUE TITLE
建立一个社区交流群，方便大家实时沟通问题

### ISSUE THREAD

**Issue by chmod777john** [Zeyi-Lin/HivisionIDPhotos#28]
这个项目确实很好，我觉得应该有很多人会喜欢用它。但我预计其中相当一部分是小白用户，可能会遇到一些问题。这些问题可能非常微小，在群里实时有人回复的话会比较好，也有利于建立活跃的社区来听取用户意见。

不是引流，单纯觉得这个项目确实需要一个社区，并且我也想参与到社区贡献中，后续如果作者需要的话，我愿意转让群管理。

![image](https://github.com/user-attachments/assets/81b99137-5fb0-4509-a26a-c6a67ae8c873)

**Comment by Zeyi-Lin** [comment]
感谢，我有时间会在群里跟大家交流

**Comment by Zeyi-Lin** [comment]
群链接已加到README
