### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by lexluthors** [Zeyi-Lin/HivisionIDPhotos#32]
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.15.0 (from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0)
ERROR: No matching distribution found for onnxruntime==1.15.0

**Comment by Zeyi-Lin** [comment]
The project is mainly tested on python3.10, other versions of python may encounter situations where dependencies cannot be found.

Consider optimizing this in the future. :)
