### ISSUE TITLE
Dockrfile构建的如何更新

### ISSUE THREAD

**Issue by nageshuizeii** [Zeyi-Lin/HivisionIDPhotos#33]
感谢开发，已在群晖中成功部署后使用，但看更新日志2024.9.2: 更新调整照片 KB 大小，而hivision_modnet.onnx版本为Jul 3, 2023。

请问如何更新，谢谢！

**Comment by Zeyi-Lin** [comment]
最新的更新没有改动`hivision_modnet.onnx`，所以在最新的commit用Dockerfile构建即可 :)

The latest update did not modify `hivision_modnet.onnx`, so you can build with Dockerfile in the latest commit :)
