### ISSUE TITLE
效果与预想的不太一致

### ISSUE THREAD

**Issue by lucasjinreal** [Zeyi-Lin/HivisionIDPhotos#34]
<img width="1122" alt="image" src="https://github.com/user-attachments/assets/d3c6b264-3522-4979-8368-a17b14afd87c">

**Comment by ChaoII** [comment]
和wps看图中的智能证件照还差很多

**Comment by diantu188** [comment]
抠图模型训练度不够

**Comment by Zeyi-Lin** [comment]
这个模型训练的比较早了：）

我在这周增加一些新的sota抠图模型，以及云端抠图API的拓展

**Comment by lucasjinreal** [comment]
看宣传图还以为某种diffusion之类的生图来做ID，但是看起来就是抠图加换背景。anyway，还是非常欣赏开源工作

**Comment by liuqasd** [comment]
原来目前只能把图扣下来

**Comment by Zeyi-Lin** [comment]
是的，这个项目比较偏工程与业务落地，主要通过 抠图+检测+裁剪规则 来制作证件照。

其实这次能这么受开源社区的欢迎，我也非常惊喜和意外，没想到自己几年前的项目会突然火起来。思考来，我觉得这也符合开源的理念，不一定要多么高大上，只要用开源开放的方式，让技术民主化，普惠更多人，就有机会受到欢迎。

关于项目的未来，我可能更多希望它成为一个工具类项目（偏Adobe），集成其他优秀的matting模型和diffusion模型，让人人都能拥有自己的“线上海马体”。

**Comment by jona95** [comment]
> 这个模型训练的比较早了：）
> 
> 我在这周增加一些新的sota抠图模型，以及云端抠图API的拓展
> 
> This model was trained earlier:)
> 
> I'm adding some new sota Matting models this week, as well as extensions to the cloud Matting API

期待更优秀的抠图模型！我测试也是有的照片头发少一块、有的照片耳朵少一块，抠图还不完美。

**Comment by Zeyi-Lin** [comment]
拓展了很多新模型和新功能，详见README更新日志。
