### ISSUE TITLE
docker镜像只支持arm64

### ISSUE THREAD

**Issue by Jio0oiJ** [Zeyi-Lin/HivisionIDPhotos#40]
![image](https://github.com/user-attachments/assets/cb02d2eb-4523-4055-b0a6-b3b7f2de5c0a)
希望添加其他平台，至少amd64要有吧

**Comment by Zeyi-Lin** [comment]
Planned: #29

**Comment by Zeyi-Lin** [comment]
已支持AMD64，在研究如何支持双平台。

Supports AMD64. Researching how to support dual platforms.
