### ISSUE TITLE
windows上docker 运行报错

### ISSUE THREAD

**Issue by dexterrrrrcc** [Zeyi-Lin/HivisionIDPhotos#43]
C:\Users\thinkpad>docker run -p 7860:7860 hivision_idphotos
/usr/local/lib/python3.10/dist-packages/gradio_client/documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Parallel'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
/usr/local/lib/python3.10/dist-packages/gradio_client/documentation.py:106: UserWarning: Could not get documentation group for <class 'gradio.mix.Series'>: No known documentation group for module 'gradio.mix'
  warnings.warn(f"Could not get documentation group for {cls}: {exc}")
/app/app.py:324: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  img_input = gr.Image().style(height=350)
/app/app.py:409: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  img_output_standard = gr.Image(label="标准照").style(height=350)
/app/app.py:410: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  img_output_standard_hd = gr.Image(label="高清照").style(height=350)
/app/app.py:411: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  img_output_layout = gr.Image(label="六寸排版照").style(height=350)

**Comment by Zeyi-Lin** [comment]
这个不是报错，是warning。另外，实际上服务已经开起来了，可以试试：

> 在你的本地访问 http://127.0.0.1:7860/ 即可使用。

This is not an error, it's a warning. In addition, the service has actually started and you can try:

> You can access http://127.0.0.1:7860/ on your local machine to use it.
