### ISSUE TITLE
HelloGitHub 徽章

### ISSUE THREAD

**Issue by 521xueweihan** [Zeyi-Lin/HivisionIDPhotos#47]
🎉 恭喜！您的[项目](https://hellogithub.com/repository/8ea1457289fb4062ba661e5299e733d6)已被 HelloGitHub 社区收录和推荐，现邀请您加入 HelloGitHub 徽章计划。加入后，您将获得以下特权：

- 社区认可: 徽章代表你的项目已通过 HelloGitHub 社区的严格筛选，并获得推荐。
- 提高曝光: 佩戴徽章后，你的项目将获得更多推荐流量，吸引更多用户和贡献者。
- 增强互动: 用户可通过徽章快速了解项目，并与之互动（点赞、评论、收藏）。
- 收集反馈: 获取广大用户的真实反馈，持续优化你的项目。
- 特殊标识: 认证后，你的评论将有显著标识，并获得置顶优先权。

📌 [立即点击](https://hellogithub.com/repository/8ea1457289fb4062ba661e5299e733d6/embed) 完成徽章佩戴，加入 HelloGitHub 徽章计划，让你的开源项目绽放更耀眼的光彩。

**Comment by Zeyi-Lin** [comment]
谢谢HelloGitHub社区的推荐，祝国内开源社区生态越来越好

**Comment by 521xueweihan** [comment]
@Zeyi-Lin 感谢您的支持和认领，认证已审核通过，如果有任何问题欢迎联系我。

<img width="765" alt="image" src="https://github.com/user-attachments/assets/abd32c47-e267-4080-9c19-8c1da1cdf320">
