### ISSUE TITLE
预设尺寸标注长宽的像素和厘米

### ISSUE THREAD

**Issue by muxinxy** [Zeyi-Lin/HivisionIDPhotos#49]
预设尺寸标注长宽的像素和厘米，方便找到合适的尺寸

**Comment by Zeyi-Lin** [comment]
好想法，会在代码中更新上

**Comment by Zeyi-Lin** [comment]
已增加：https://github.com/Zeyi-Lin/HivisionIDPhotos/commit/a18ce6957a0ec4dbf310eb3e0975f90620b53c2f
