### ISSUE TITLE
增加水印功能（非商用）

### ISSUE THREAD

**Issue by peterzyk** [Zeyi-Lin/HivisionIDPhotos#55]
可以增加一个水印功能嘛？

具体应用场景：

某些单位招聘时候会需要提供照片+身份证号，信息有些敏感，所以如果有个水印就很方便了。

同时出去住民宿，会要求提供身份证照片。

现在有同类功能的产品/网站，如果这里集成了，关于照片/证件类的核心需求基本就全了

大佬，让这个项目变得再伟大一些吧，膜拜

**Comment by Zeyi-Lin** [comment]
感谢你提出的需求，我会考虑在后续更新

**Comment by Zeyi-Lin** [comment]
水印功能已增加
