### ISSUE TITLE
上传大尺寸照片导致服务器失联

### ISSUE THREAD

**Issue by houhoufm** [Zeyi-Lin/HivisionIDPhotos#76]
之前相机拍摄的证件照，点击制作后，一直处理中。。。然后服务器就失联了。
可以设置内存限制吗，或者给一个内存限制的参考？

我的照片文件尺寸：
![图片](https://github.com/user-attachments/assets/20e8f1e5-7607-485a-9120-47823edf425a)

我的服务器：阿里云2h-4g-30m

**Comment by Zeyi-Lin** [comment]
问题解决了吗？同时你的截图也启发了我，可以有一个设置照片dpi的选项。

**Comment by houhoufm** [comment]
已解决，谢谢：等了一会儿，服务器自己回复过来啦
