### ISSUE TITLE
拍照功能如何使用？

### ISSUE THREAD

**Issue by Insulinocytus** [Zeyi-Lin/HivisionIDPhotos#77]
- 上传文件
- 连接Web Camera
- 读取剪贴板

我尝试使用第二种方式直接通过我电脑的Web Camera拍照，但是我没看到任何拍照按钮。
如果我直接点击【开始制作】，就会提示Error，log显示的内容和不上传图片直接点开始制作出现的log一致。
是我没找到拍照按钮吗？

**Comment by Zeyi-Lin** [comment]
<img width="143" alt="image" src="https://github.com/user-attachments/assets/d7fcaf1d-00b9-4534-b9a6-f54423dc0f8d">

拍照按钮在这里:)

**Comment by Insulinocytus** [comment]
My bad.
我阿尔兹海默了，鼠标点击总是点到右边的倒三角，弄得我以为这个按钮只能用来切换摄像头。

**Comment by Zeyi-Lin** [comment]
没事，确实不太好找，Gradio的产品设计师也有锅

**Comment by Insulinocytus** [comment]
> Gradio的产品设计师也有锅

确实，一般来说一个按钮如果具有可展开选项的时候，应该在倒三角和按钮描述中间加一条竖线。
这代表按钮本身是一个功能，同时倒三角里可以看到其他扩展功能。

如果没有竖线，我会认为这个倒三角和前面的描述为同一按钮。
![1](https://github.com/user-attachments/assets/24c169da-7d28-4bdd-8b59-603b816db8bf)

**Comment by Zeyi-Lin** [comment]
> > Gradio的产品设计师也有锅
> 
> 确实，一般来说一个按钮如果具有可展开选项的时候，应该在倒三角和按钮描述中间加一条竖线。 这代表按钮本身是一个功能，同时倒三角里可以看到其他扩展功能。
> 
> 如果没有竖线，我会认为这个倒三角和前面的描述为同一按钮。 ![1](https://private-user-images.githubusercontent.com/171487220/365421330-24c169da-7d28-4bdd-8b59-603b816db8bf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODA5NTMsIm5iZiI6MTcyNTc4MDY1MywicGF0aCI6Ii8xNzE0ODcyMjAvMzY1NDIxMzMwLTI0YzE2OWRhLTdkMjgtNGJkZC04YjU5LTYwM2I4MTZkYjhiZi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwNzMwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGI4Y2MwZjcyZTQzODMyNWJhZTNlOGM3NzY3NTQxOWVjOWNlOGYyZDg2OGVkZjVhOTBiZTQzNmE3MTQwYjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1fI97GRbk4xgoyNdm8eN9VACJsPnx-_5OTL8jSDEsM4) [ ![1](https://private-user-images.githubusercontent.com/171487220/365421330-24c169da-7d28-4bdd-8b59-603b816db8bf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODA5NTMsIm5iZiI6MTcyNTc4MDY1MywicGF0aCI6Ii8xNzE0ODcyMjAvMzY1NDIxMzMwLTI0YzE2OWRhLTdkMjgtNGJkZC04YjU5LTYwM2I4MTZkYjhiZi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwNzMwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGI4Y2MwZjcyZTQzODMyNWJhZTNlOGM3NzY3NTQxOWVjOWNlOGYyZDg2OGVkZjVhOTBiZTQzNmE3MTQwYjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1fI97GRbk4xgoyNdm8eN9VACJsPnx-_5OTL8jSDEsM4) ](https://private-user-images.githubusercontent.com/171487220/365421330-24c169da-7d28-4bdd-8b59-603b816db8bf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODA5NTMsIm5iZiI6MTcyNTc4MDY1MywicGF0aCI6Ii8xNzE0ODcyMjAvMzY1NDIxMzMwLTI0YzE2OWRhLTdkMjgtNGJkZC04YjU5LTYwM2I4MTZkYjhiZi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwNzMwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGI4Y2MwZjcyZTQzODMyNWJhZTNlOGM3NzY3NTQxOWVjOWNlOGYyZDg2OGVkZjVhOTBiZTQzNmE3MTQwYjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1fI97GRbk4xgoyNdm8eN9VACJsPnx-_5OTL8jSDEsM4) [ ](https://private-user-images.githubusercontent.com/171487220/365421330-24c169da-7d28-4bdd-8b59-603b816db8bf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODA5NTMsIm5iZiI6MTcyNTc4MDY1MywicGF0aCI6Ii8xNzE0ODcyMjAvMzY1NDIxMzMwLTI0YzE2OWRhLTdkMjgtNGJkZC04YjU5LTYwM2I4MTZkYjhiZi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwNzMwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGI4Y2MwZjcyZTQzODMyNWJhZTNlOGM3NzY3NTQxOWVjOWNlOGYyZDg2OGVkZjVhOTBiZTQzNmE3MTQwYjQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1fI97GRbk4xgoyNdm8eN9VACJsPnx-_5OTL8jSDEsM4)

你是对的

**Comment by Insulinocytus** [comment]
https://github.com/gradio-app/gradio/issues/9290

已提交给gradio
