### ISSUE TITLE
人脸数量不等于1如何解决，图中只有一个人脸啊

### ISSUE THREAD

**Issue by blacksino** [Zeyi-Lin/HivisionIDPhotos#8]
如题

**Comment by JasonG98** [comment]
我也是，是不是模型有问题啊，我都拍了五张自拍了。网上爬一张马斯克就能识别，我的自拍就识别不了。

**Comment by Zeyi-Lin** [comment]
人脸检测模型选的是 https://github.com/ipazc/mtcnn ，考虑更换更好的模型

**Comment by Zeyi-Lin** [comment]
已添加face++模型，在最新的Demo中可体验
