### ISSUE TITLE
使用api服务，请求时报错

### ISSUE THREAD

**Issue by doom-9** [Zeyi-Lin/HivisionIDPhotos#94]
TypeError: IDCreator.__call__() got an unexpected keyword argument 'top_distance_max'

![image](https://github.com/user-attachments/assets/420cce45-6710-4e5b-ad41-9a03d577fb89)
![image](https://github.com/user-attachments/assets/75812d4c-7448-4410-a529-b326d5bbbc85)

**Comment by Zeyi-Lin** [comment]
Thank you for your feedback, it has been modified.
感谢你的反馈，已修改
